FairlyLinearDynamics/YoCode

- Tests/FileChangeCheckerTests.cs
- Tests/GitCheckTests.cs
- Tests/PathManagerTests.cs
- YoCode/FileChangeChecker.cs
- YoCode/GitCheck.cs
- YoCode/IPathManager.cs
- YoCode/PathManager.cs
- YoCode/Program.cs
1) Changed the name of Directory class to PathManager
2) Changed the name of IDirectory class to IPathManager
3) Added a check for whether the directory exists
4) REPOSITORY_PATH is now initialized in the constructor (and passed as a parameter when creating the instance) instead of being hardcoded
> GitCheck vol.2

- YoCode/CommandLineArguments/CommandErrorChecking.cs
- YoCode/PrintToConsole.cs
- YoCode/Program.cs
> Help message implemented

- Tests/PathManagerTests.cs
- YoCode/DuplicationCheck.cs
- YoCode/FileImport.cs
- YoCode/PathManager.cs
- YoCode/Program.cs
Updated DuplicationCheck class to output its results to console
> output_for_duplication

- YoCode/HelperMethods.cs
- YoCode/ProcessRunner.cs
- YoCode/ProjectBuilder.cs
- YoCode/ProjectRunner.cs
Refactored ProcessRunner, finished Project Runner
> I32 run applicants code

- Tests/GitCheckTests.cs
- Tests/HelperMethodsTest.cs
- Tests/TestCountCheckTests.cs
- Tests/YoCode_XUnit.csproj
- YoCode.sln
- YoCode/DuplicationCheck.cs
- YoCode/GitCheck.cs
- YoCode/HelperMethods.cs
- YoCode/Program.cs
- YoCode/YoCode.csproj
- YoCode/appsettings.json
Added tests for HelperMethods
Added the config file and initialized it
Fixed minor errors
> 07 16refactoring and writing tests

- YoCode/CommandLineArguments/CommandLineParser.cs
- YoCode/DuplicationCheck.cs
- YoCode/ProcessRunner.cs
- YoCode/Program.cs
- YoCode/ProjectRunner.cs
> Changed ProjectRunner

- YoCode/Program.cs
- YoCode/ProjectBuilder.cs
- YoCode/appsettings.json
> Output for project builder

- .gitignore
- Tests/GitCheckTests.cs
- Tests/YoCode_XUnit.csproj
- YoCode/DuplicationCheck.cs
- YoCode/FeatureEvidence.cs
- YoCode/FeatureRunner.cs
- YoCode/FileChangeChecker.cs
- YoCode/GitCheck.cs
- YoCode/PrintToConsole.cs
- YoCode/ProcessDetails.cs
- YoCode/ProcessRunner.cs
- YoCode/Program.cs
- YoCode/ProjectBuilder.cs
- YoCode/ProjectRunner.cs
- YoCode/TestCountCheck.cs
…directory is valid in ProjectRunner. Cleaned up code inother classes
> TimoutsAndRefactor

- YoCode/DuplicationCheck.cs
- YoCode/FeatureRunner.cs
- YoCode/GitCheck.cs
- YoCode/Program.cs
- YoCode/TestCountCheck.cs
This is to allow it to be mocked so more tests can be written.
> Extracted interface for featureRunner

- YoCode/DuplicationCheck.cs
- YoCode/GitCheck.cs
- YoCode/Program.cs
- YoCode/TestCountCheck.cs
- YoCode/messages.Designer.cs
- YoCode/messages.resx
> I69 fix output bugs

- YoCode/DuplicationCheck.cs
- YoCode/FeatureEvidence.cs
- YoCode/FeatureRunner.cs
- YoCode/GitCheck.cs
- YoCode/ProcessRunner.cs
- YoCode/Program.cs
- YoCode/ProjectBuilder.cs
- YoCode/ProjectRunner.cs
- YoCode/TestCountCheck.cs
> I64 refactoring

- YoCode/Program.cs
- YoCode/ProjectBuilder.cs
- YoCode/ProjectRunner.cs
- YoCode/TestCountCheck.cs
> I81-CleanBuildOutput

- .gitignore
- YoCode/Output.cs
- YoCode/Program.cs
- YoCode/YoCode.csproj
- YoCode/appsettings.json
- YoCode/messages.Designer.cs
- YoCode/messages.resx
Removed appsettings.json from git. Fixed bug #79
> i79-NoAppsettingsBug

- YoCode/Output/Output.cs
Small change, that will print out welcoming message to the console before proceeding with actual program's logic
> Welcoming message is printed instantly

- YoCode/Program.cs
- YoCode/ProjectBuilder.cs
- YoCodeAutomatedTests/TestHelperMethods.cs
Made YoCode clean build files before reading all files. changed the last line to look for in automated tests asynch process runner. #105
> i105-FileChangedCheckerShowsIncorrectFiles

- YoCode/Output/Output.cs
- YoCode/Program.cs
> Quick fix to issue with output being unordered

- YoCode/HTMLFetcher.cs
- YoCode/Program.cs
- YoCode/UnitConverterCheck.cs
> I29 bad input check

- YoCode/FeatureRunner.cs
- YoCode/FileImport.cs
- YoCode/ProcessRunner.cs
- YoCode/YoCode.csproj
> I93 process kill

- Tests/PathManagerTests.cs
- Tests/UICheckTests.cs
- YoCode/DuplicationCheck.cs
- YoCode/FileChangeChecker.cs
- YoCode/IPathManager.cs
- YoCode/Program.cs
> I11 special dup

- YoCode/Output/WebElementBuilder.cs
- YoCode/Output/WebWriter.cs
- YoCode/messages.Designer.cs
- YoCode/messages.resx
> I112 html style

- YoCode/messages.Designer.cs
- YoCode/messages.resx
Fixes to the javascript of html report
> Fixed html report spacing of evidences

- YoCode/Program.cs
> Code coverage check runs on a new thread

- YoCode/HtmlReportLauncher.cs
- YoCode/Program.cs
> I132 auto opener

- YoCode/LoadingAnimation.cs
- YoCode/Program.cs
- YoCode/UnitConverterCheck.cs
- YoCode/messages.Designer.cs
- YoCode/messages.resx
> Loading animation

- YoCode/HtmlReportLauncher.cs
- YoCode/LoadingAnimation.cs
- YoCode/Output/CompositeWriter.cs
- YoCode/Output/ConsoleWriter.cs
- YoCode/Output/IPrint.cs
- YoCode/Output/Output.cs
- YoCode/Output/WebElementBuilder.cs
- YoCode/Output/WebWriter.cs
- YoCode/Program.cs
- YoCode/messages.Designer.cs
- YoCode/messages.resx
Fixes for HTML and Console reports
> Html update

- YoCode/CommandLineArguments/CommandLineParser.cs
- YoCode/CommandLineArguments/CommandNames.cs
- YoCode/CommandLineArguments/InputResult.cs
- YoCode/Output/Output.cs
- YoCode/Output/WebWriter.cs
- YoCode/Program.cs
- YoCode/messages.Designer.cs
- YoCode/messages.resx
- YoCodeAutomatedTests/BuildTests.cs
> New parameters

- YoCode/messages.resx
> Chrome now prints properly, thanks Mike 

- YoCode/ProjectBuilder.cs
> Project Run Issue

- YoCode/ConsoleCloseHandler.cs
- YoCode/FrontEndCheck.cs
> Geckodriver is now killed properly

- YoCode/FeatureRunner.cs
- YoCode/ProcessRunner.cs
- YoCode/Program.cs
- YoCode/ProjectRunner.cs
- YoCodeAutomatedTests/BuildTests.cs
- YoCodeAutomatedTests/HelpMessageTest.cs
> NotifyLeftOverProcesses

- YoCode/TestCountCheck.cs
> Added error messages for TestCountCheck

- YoCode/TestCountCheck.cs
TestCountCheck now runs in the right directory #176
> I176 testcountcheck wrongdirectory

- YoCode/FileChangeFinder.cs
- YoCode/GitCheck.cs
- YoCode/Output/WebWriter.cs
- YoCode/Program.cs
- YoCode/Results.cs
- YoCodeAutomatedTests/BuildTests.cs
> I171 crash with waters commit

- YoCode/FeatureDetailsStorage.cs
- YoCode/FeatureWeightings/JuniorWeightings.json
- YoCode/FeatureWeightings/OriginalWeightings.json
- YoCode/Program.cs
- YoCode/Results.cs
- YoCode/UIKeywords.cs
- YoCode/UnitConverterCheck.cs
> Fixed solution check error

- YoCode/ConsoleCloseHandler.cs
- YoCode/ExceptionHandler.cs
- YoCode/Program.cs
#167 
Added an unhandled exception handler which tries to close selenium and unitconverterwebapp if an unhandled exception occurs
> i167-UnhandledExceptionHandler

- YoCode/Output/WebElementBuilder.cs
- YoCode/Output/WebWriter.cs
#187 
HTML report now shows an en dash when a feature could not be checked
> i187-NoScoreForThirdState

- YoCode/Output/WebWriter.cs
#190 
YoCode will now open the correct report when --output is specified
> i190-WrongReport

- YoCodeAutomatedTests/BuildTests.cs
- YoCodeAutomatedTests/HelpMessageTest.cs
- YoCodeAutomatedTests/TestHelperMethods.cs
Try to make it easier to see what exactly is happening when tests run, to rule out certain types of problem.
> Add some debug info to automated tests

- YoCode/CodeCoverageCheck.cs
- YoCode/DuplicationCheck.cs
- YoCode/FeatureEvidence.cs
- YoCode/FileChangeFinder.cs
- YoCode/GitCheck.cs
- YoCode/Output/FeatureData.cs
- YoCode/Output/Output.cs
- YoCode/Output/WebElementBuilder.cs
- YoCode/Output/WebWriter.cs
- YoCode/TestCountCheck.cs
- YoCode/UnitConverterCheck.cs
- YoCode/UserInterfaceChecks/UIBadInputChecker.cs
- YoCode/UserInterfaceChecks/UICodeCheck.cs
- YoCode/UserInterfaceChecks/UIConversionCheck.cs
- YoCode/UserInterfaceChecks/UIFeatureImplemented.cs
- YoCode/messages.Designer.cs
- YoCode/messages.resx
> Added helper messages

- Tests/DuplicationCheckTests.cs
- Tests/UICheckTests.cs
- YoCode/CodeCoverageCheck.cs
- YoCode/DotCover.cs
- YoCode/DuplicationCheck.cs
- YoCode/FeatureEvidence.cs
- YoCode/FeatureRunner.cs
- YoCode/FileChangeFinder.cs
- YoCode/GitCheck.cs
- YoCode/Output/Output.cs
- YoCode/Output/WebElementBuilder.cs
- YoCode/Output/WebWriter.cs
- YoCode/ProjectBuilder.cs
- YoCode/ProjectRunner.cs
- YoCode/Results.cs
- YoCode/TestCountCheck.cs
- YoCode/UnitConverterCheck.cs
- YoCode/UserInterfaceChecks/UIBadInputChecker.cs
- YoCode/UserInterfaceChecks/UICodeCheck.cs
- YoCode/UserInterfaceChecks/UIConversionCheck.cs
- YoCode/UserInterfaceChecks/UIFeatureImplemented.cs
Also includes the missing formatting that apparently happened in PR #193.
> Refactoring session

- YoCode/ProcessRunner.cs
- YoCodeAutomatedTests/BuildTests.cs
- YoCodeAutomatedTests/HelpMessageTest.cs
- YoCodeAutomatedTests/TestHelperMethods.cs
Temporarily increased Process timeout to 50s from 40 until we sort out the threads. Updated automated tests to check the html report instead of console output, standard and error output is collected for debugging purposes now
#205
> i205-HTMLAutomatedTests

- YoCode/Checks/UserInterfaceChecks/UIFeatureImplemented.cs
- YoCode/EvidenceBuilders/FileDiffEvidenceBuilder.cs
- YoCode/EvidenceBuilders/UIScreenShotEvidenceBuilder.cs
- YoCode/Output/Output.cs
- YoCode/Output/WebElementBuilder.cs
- YoCode/Program.cs
- YoCode/messages.resx
> I214 ui screen shot

- YoCode/Output/CompositeWriter.cs
- YoCode/Output/ConsoleWriter.cs
- YoCode/Output/IPrint.cs
- YoCode/Output/Output.cs
- YoCode/Output/WebElementBuilder.cs
- YoCode/Output/WebWriter.cs
- YoCode/Program.cs
- YoCode/messages.resx
> I206 test type html

- YoCode/DotCover.cs
> Fixed automated tests

- YoCode/Checks/CodeCoverageCheck.cs
- YoCode/Checks/TestCountCheck.cs
- YoCode/ProcessRunner.cs
- YoCode/ProjectBuilder.cs
#227 Still sometimes sets TestCountCheck to inconclusive... (should be sorted when we completely refactor CheckManager?)
> I227 test count issue

- YoCode/Checks/UserInterfaceChecks/UIConversionCheck.cs
- YoCode/FeatureInfo/Feature.cs
- YoCode/FeatureInfo/FeatureTitleStorage.cs
- YoCode/ProjectBuilder.cs
- YoCode/ProjectRunner.cs
UIConversionCheck was not setting failed when it should, it was behaving as if the check was inconclusive.
The main thing was #230 though, which meant the gateway check system was just broken.
> Fix #230 and also a bug in UIConversionCheck

- YoCode/CheckManager.cs
- YoCode/Checks/BadInputCheck.cs
- YoCode/Checks/CodeCoverageCheck.cs
- YoCode/Checks/ProjectBuilder.cs
- YoCode/Checks/ProjectRunner.cs
- YoCode/Checks/TestCountCheck.cs
- YoCode/Checks/UnitConverterCheck.cs
- YoCode/Checks/UserInterfaceChecks/UICheck.cs
- YoCode/FeatureInfo/FeatureEvidence.cs
- YoCode/FeatureWeightings/JuniorWeightings.json
- YoCode/FeatureWeightings/OriginalWeightings.json
- YoCode/Program.cs
- YoCode/Results.cs
I have finished off our group refactoring from Friday. I _think_ this works, and answers #243.
> Continuations

- YoCode/LoadingAnimation.cs
- YoCode/Program.cs
1. Removed LoadingAnimation from its Thread
2. Put it in the Task
3. Added cancellation token
> I244 remove loading animation from thread

- YoCode/Checks/CodeCoverageCheck.cs
Maybe this wasn't causing a problem but it feels wrong so I'm fixing it anyway.
> Code coverage now writes to tmp file

- YoCode/FeatureInfo/FeatureTitleStorage.cs
Changed Feature names to be more specific. Feel free to criticize these and suggest your own.
> I248 change feature names

- YoCodeAutomatedTests/BuildTests.cs
- YoCodeAutomatedTests/HelpMessageTest.cs
- YoCodeAutomatedTests/TestHelperMethods.cs
Tests now write to the output directory, not the binary directory, just in case that was causing issues (I can't see why it would but some of the output from the VSTS agent suggested it could be, so I got scared).
> Some last minute tweaks to automated tests
